[package]
name = "ffi"
version = "0.1.0"
authors = ["Steven Jimenez <steven@stevethedev.com>"]
edition = "2018"

[lib]
crate-type = ["dylib"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
